// Door tablet, driven by real taps, real keypad presses and real signature drags (dd1). Runs on chromium-tablet and
// webkit-tablet (1024×768, touch).   E2E_PORT=7804 npx playwright test tests/door
import { expect, test } from '@playwright/test'
import {
  api, assertNoThirdParty, at, bearer, CENTRE, doorToken, drawSignature, EDUCATOR_PIN, fresh, keypad, presenceViaApi, shot,
  signInViaApi, signOutViaApi, staffToken, STATE_RGB, stateColour, SUPERVISOR_PIN, supervisorToken, tap,
} from '../helpers.mjs'

const card = (page, id) => page.locator(`button.child[data-child="${id}"]`)
const person = (page, id) => page.locator(`button.person[data-person="${id}"]`)

test.afterEach(async ({ context }) => assertNoThirdParty(context))

async function setUpTablet(page) {
  await page.goto('/door/')
  await expect(page.getByRole('heading', { name: 'Set up this tablet' })).toBeVisible()
  await keypad(page, SUPERVISOR_PIN, page.locator('#pin-enter'))
  await expect(card(page, 'c_ava')).toBeVisible()
}

// Keys by real taps, then Enter; resolves with the unlock response.
async function unlockWith(page, pin) {
  for (const d of pin) await tap(page, page.locator(`button.key[data-key="${d}"]`), `key ${d}`)
  const [resp] = await Promise.all([
    page.waitForResponse((r) => r.url().endsWith('/api/door/unlock')),
    tap(page, page.locator('#pin-enter'), 'Enter'),
  ])
  return resp
}

async function signOnPad(page) {
  await expect(page.getByText('Sign here with your finger')).toBeVisible()
  await expect(page.locator('#pad-done'), 'Done is disabled before there is ink').toBeDisabled()
  await drawSignature(page, page.locator('#pad'))
  await expect(page.locator('#pad-done')).toBeEnabled()
  await tap(page, page.locator('#pad-done'), 'Done')
}

test('setup: a wrong PIN says so and the unlock answer is 401; an educator PIN is refused; the supervisor PIN opens the grid', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  await page.goto('/door/')
  await expect(page.getByRole('heading', { name: 'Set up this tablet' })).toBeVisible()
  await expect(page.getByText(CENTRE).first()).toBeVisible()
  await expect(page.locator('.sample-badge').first()).toBeVisible()
  await shot(page, testInfo, 'door', '1-setup-keypad')
  const wrong = await unlockWith(page, '9999')
  expect(wrong.status(), 'a wrong PIN is refused by the Worker').toBe(401)
  await expect(page.locator('#pin-error')).toHaveText('That PIN is not right.')
  const educator = await unlockWith(page, EDUCATOR_PIN)
  expect(educator.status()).toBe(403)
  await expect(page.locator('#pin-error')).toHaveText('Only the supervisor can set up this tablet.')
  await shot(page, testInfo, 'door', '1-setup-refused')
  const ok = await unlockWith(page, SUPERVISOR_PIN)
  expect(ok.status()).toBe(200)
  await expect(card(page, 'c_ava')).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('daycare-day-sheet:door-token'))).toMatch(/^[A-Za-z0-9_-]{43}$/)
  await page.reload()
  await expect(card(page, 'c_ava'), 'the tablet stays set up after a reload').toBeVisible()
})

test('grid: every SAMPLE child with the status the API gives, Isla under Not booked today, and the room chips filter', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  await setUpTablet(page)
  const r = await api(request, 'GET', '/api/door/children', null, bearer(await doorToken(request)))
  expect(r.body.children).toHaveLength(19)
  await expect(page.locator('button.child')).toHaveCount(19)
  for (const c of r.body.children) {
    await expect(card(page, c.id)).toHaveAttribute('data-status', c.status)
    await expect(card(page, c.id)).toContainText(c.name)
    await expect(card(page, c.id)).toContainText(c.status_label)
  }
  await expect(page.locator('#not-booked')).toContainText('Not booked today')
  await expect(page.locator('#not-booked button.child')).toHaveCount(1)
  await expect(page.locator('#not-booked button.child[data-child="c_isla"]')).toHaveAttribute('data-status', 'not_booked')
  await expect(page.locator('#children button.child[data-status="not_in_yet"]')).toHaveCount(18)
  await expect(page.locator('#date-line')).toHaveText('Monday, September 14')
  await expect(page.locator('#time-line')).toHaveText('9:00 AM')
  await shot(page, testInfo, 'door', '2-grid')
  await tap(page, page.locator('button.chip[data-room="r_toddler"]'), 'Toddler room chip')
  await expect(page.locator('button.child')).toHaveCount(6)
  await expect(page.locator('#app'), 'no stray text in the filtered grid').not.toContainText(/null|undefined/)
  await expect(page.locator('button.chip[data-room="r_toddler"]')).toHaveAttribute('aria-pressed', 'true')
  await tap(page, page.locator('button.chip[data-room="all"]'), 'All chip')
  await expect(page.locator('button.child')).toHaveCount(19)
})

test('sign in by real taps and a drawn signature: the card says In since 9:00 AM, and the API and the register hold the visit with its signature', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  await setUpTablet(page)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await expect(page.locator('#sheet')).toContainText('Ava M. (SAMPLE)')
  await shot(page, testInfo, 'door', '3-sheet-1-action')
  await tap(page, page.locator('#action-in'), 'Sign in')
  await expect(page.getByText('Who is dropping off?')).toBeVisible()
  await shot(page, testInfo, 'door', '3-sheet-2-who')
  await tap(page, person(page, 'p_ava_mother'), 'Sarah')
  const box = await page.locator('#pad').boundingBox()
  expect(box.width, 'pad width').toBeGreaterThanOrEqual(600)
  expect(box.height, 'pad height').toBeGreaterThanOrEqual(200)
  await expect(page.locator('#pad-done')).toBeDisabled()
  await shot(page, testInfo, 'door', '3-sheet-3-pad')
  await drawSignature(page, page.locator('#pad'))
  await expect(page.locator('#pad-done')).toBeEnabled()
  await shot(page, testInfo, 'door', '3-sheet-3-pad-signed')
  const [resp] = await Promise.all([
    page.waitForResponse((r) => r.url().endsWith('/api/door/children/c_ava/in')),
    tap(page, page.locator('#pad-done'), 'Done'),
  ])
  expect(resp.status()).toBe(201)
  const answer = await resp.json()
  const confirm = page.locator('#confirm')
  await expect(confirm).toContainText('Signed in')
  await expect(confirm).toContainText('9:00 AM')
  await expect(confirm).toContainText('by Sarah M. (SAMPLE)')
  await tap(page, page.locator('#confirm-done'), 'Done on the confirmation')
  await expect(card(page, 'c_ava')).toContainText('In since 9:00 AM')
  await expect(card(page, 'c_ava')).toHaveAttribute('data-status', 'in')
  const d = await api(request, 'GET', '/api/door/children/c_ava', null, bearer(await doorToken(request)))
  expect([d.body.child.status, d.body.child.status_label]).toEqual(['in', 'In since 9:00 AM'])
  expect(d.body.visit.in_by.id).toBe('p_ava_mother')
  expect(d.body.visit.in_signature_svg).toBe(answer.visit.in_signature_svg)
  expect((d.body.visit.in_signature_svg.match(/ L\d+ \d+/g) || []).length, 'the stored signature is the drawn stroke').toBeGreaterThan(6)
  const reg = await api(request, 'GET', '/api/office/register?date=2026-09-14&room_id=r_infant', null, bearer(await supervisorToken(request)))
  expect(reg.body.rows.map((row) => row.child.name)).toEqual(['Ava M. (SAMPLE)'])
  expect(reg.body.rows[0].visits[0].in_signature_svg).toMatch(/^<svg [^>]*><path d="M\d+ \d+( L\d+ \d+)+"/)
})

test('the ratio moment on the tablet: with Marie and three infants in, signing Owen in shows the red over banner', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  await presenceViaApi(request, await staffToken(request, EDUCATOR_PIN), 'r_infant')
  const door = await doorToken(request)
  for (const [child, who] of [['c_ava', 'p_ava_mother'], ['c_liam', 'p_liam_mother'], ['c_nora', 'p_nora_mother']]) {
    await signInViaApi(request, door, child, who)
  }
  await setUpTablet(page)
  await expect(card(page, 'c_nora')).toHaveAttribute('data-status', 'in')
  await tap(page, card(page, 'c_owen'), 'Owen card')
  await tap(page, page.locator('#action-in'), 'Sign in')
  await tap(page, person(page, 'p_owen_mother'), 'Megan')
  await signOnPad(page)
  const banner = page.locator('#over-banner')
  await expect(banner, 'the over banner').toHaveText('Infant room is over the ratio. Tell the room staff.')
  await expect(banner).toHaveAttribute('role', 'alert')
  const pill = page.locator('#confirm [data-state]')
  await expect(pill).toHaveAttribute('data-state', 'over')
  expect(await stateColour(pill), 'the meter pill a person sees is the over colour').toBe(STATE_RGB.over)
  await expect(page.locator('#confirm')).toContainText('4 children, 1 staff. Over the ratio: 1 staff can have 3. Needs 1 more staff.')
  await shot(page, testInfo, 'door', '4-confirm-over-banner')
})

test('not on the list: the neighbour may drop off but is not offered at pick-up; Someone else blocks; the grandmother signs Ava out', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  await setUpTablet(page)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await tap(page, page.locator('#action-in'), 'Sign in')
  await expect(person(page, 'p_ava_neighbour'), 'the drop-off list has Rick D.').toBeVisible()
  await expect(person(page, 'p_ava_neighbour')).toContainText('Neighbour')
  await tap(page, page.locator('#back'), 'Back to the action')
  await tap(page, page.locator('#back'), 'Back to the grid')
  await expect(page.locator('#sheet')).toHaveCount(0)
  const door = await doorToken(request)
  await signInViaApi(request, door, 'c_ava', 'p_ava_mother')
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await tap(page, page.locator('#action-out'), 'Sign out')
  await expect(page.getByText('Who is picking up?')).toBeVisible()
  await expect(person(page, 'p_ava_gran')).toBeVisible()
  await expect(person(page, 'p_ava_neighbour'), 'the pick-up list does not contain Rick D.').toHaveCount(0)
  await expect(page.locator('#sheet'), 'the pick-up list does not contain Rick D.').not.toContainText('Rick D.')
  await shot(page, testInfo, 'door', '5-sheet-who-picks-up')
  await tap(page, page.locator('#someone-else'), 'Someone else')
  const block = page.locator('#not-on-list')
  await expect(block).toHaveAttribute('role', 'alert')
  await expect(block).toContainText('Not on the list')
  await expect(block).toContainText('Get the supervisor.')
  await expect(block).toContainText('Do not let Ava M. (SAMPLE) leave with someone who is not on the list.')
  await shot(page, testInfo, 'door', '5-block-not-on-list')
  const still = await api(request, 'GET', '/api/door/children/c_ava', null, bearer(door))
  expect(still.body.child.status, 'nothing was sent: Ava is still in').toBe('in')
  await tap(page, page.locator('#back'), 'Back to the list')
  await tap(page, person(page, 'p_ava_gran'), 'Joan')
  await signOnPad(page)
  await expect(page.locator('#confirm')).toContainText('Signed out')
  await expect(page.locator('#confirm')).toContainText('by Joan M. (SAMPLE)')
  await tap(page, page.locator('#confirm-done'), 'Done')
  await expect(card(page, 'c_ava')).toContainText('Gone home at 9:00 AM')
  await expect(card(page, 'c_ava')).toHaveAttribute('data-status', 'gone_home')
})

test('Add a signature: a drop-off staff recorded gets the parent\'s signature and keeps its time', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  const marie = await staffToken(request, EDUCATOR_PIN)
  const rec = await api(request, 'POST', '/api/staff/children/c_ava/in', { person_id: 'p_ava_mother' }, bearer(marie), { now: at('2026-09-14T08:05:00-02:30') })
  expect(rec.status, JSON.stringify(rec.body)).toBe(201)
  await setUpTablet(page)
  await expect(card(page, 'c_ava')).toContainText('Signature needed')
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await expect(page.locator('#sheet')).toContainText('Drop-off at 8:05 AM')
  await shot(page, testInfo, 'door', '6-add-signature')
  await tap(page, page.locator('#add-signature'), 'Add a signature')
  await expect(page.locator('#sheet')).toContainText('Sarah M. (SAMPLE), sign for the drop-off at 8:05 AM')
  await signOnPad(page)
  await expect(page.locator('#confirm')).toContainText('Signature added')
  await expect(page.locator('#confirm')).toContainText('Drop-off at 8:05 AM stays as it was.')
  const d = await api(request, 'GET', '/api/door/children/c_ava', null, bearer(await doorToken(request)))
  expect([d.body.visit.awaiting_signature, d.body.visit.in_label, d.body.visit.in_at]).toEqual([null, '8:05 AM', rec.body.visit.in_at])
  expect(d.body.visit.in_recorded_by).toEqual({ id: 's_marie', initials: 'MT' })
  expect(d.body.visit.in_signature_svg).toMatch(/<path d="M\d+ \d+( L\d+ \d+)+"/)
  await tap(page, page.locator('#confirm-done'), 'Done')
  await expect(card(page, 'c_ava')).not.toContainText('Signature needed')
})

test('Back at every step, and Done stays disabled until there is ink (a tap is only a dot)', async ({ page, context, request }) => {
  await fresh(context, request)
  await setUpTablet(page)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await tap(page, page.locator('#back'), 'Back from the action')
  await expect(page.locator('#sheet')).toHaveCount(0)
  await expect(card(page, 'c_ava')).toBeVisible()
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await tap(page, page.locator('#action-in'), 'Sign in')
  await tap(page, page.locator('#back'), 'Back from who')
  await expect(page.locator('#action-in')).toBeVisible()
  await tap(page, page.locator('#action-in'), 'Sign in')
  await tap(page, page.locator('#someone-else'), 'Someone else')
  await expect(page.locator('#not-on-list')).toContainText('Not on the list')
  await expect(page.locator('#not-on-list')).not.toContainText('Do not let', { timeout: 1000 })
  await tap(page, page.locator('#back'), 'Back from the block')
  await expect(page.getByText('Who is dropping off?')).toBeVisible()
  await tap(page, person(page, 'p_ava_father'), 'Tom')
  await expect(page.locator('#pad-done')).toBeDisabled()
  await tap(page, page.locator('#pad'), 'a single tap on the pad')
  await expect(page.locator('#pad-done'), 'a dot is not a signature').toBeDisabled()
  await tap(page, page.locator('#back'), 'Back from the pad')
  await expect(page.getByText('Who is dropping off?')).toBeVisible()
  await tap(page, person(page, 'p_ava_father'), 'Tom')
  await drawSignature(page, page.locator('#pad'))
  await expect(page.locator('#pad-done')).toBeEnabled()
  await tap(page, page.locator('#pad-clear'), 'Clear')
  await expect(page.locator('#pad-done'), 'Clear takes the ink away').toBeDisabled()
  for (let i = 0; i < 3; i++) await tap(page, page.locator('#back'), `Back ${i + 1}`)
  await expect(page.locator('#sheet')).toHaveCount(0)
  const d = await api(request, 'GET', '/api/door/children/c_ava', null, bearer(await doorToken(request)))
  expect(d.body.child.status, 'going back never signs anyone in').toBe('not_in_yet')
})

test('timers: a sheet left alone goes back to the grid after 45 s, a confirmation after 6 s', async ({ page, context, request }) => {
  await fresh(context, request)
  await page.clock.install()
  await setUpTablet(page)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await expect(page.locator('#action-in')).toBeVisible()
  await page.clock.runFor(44_000)
  await expect(page.locator('#sheet'), 'still open at 44 s').toBeVisible()
  await page.clock.runFor(2_000)
  await expect(page.locator('#sheet'), 'closed after 45 s alone').toHaveCount(0)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await tap(page, page.locator('#action-in'), 'Sign in')
  await tap(page, person(page, 'p_ava_mother'), 'Sarah')
  await signOnPad(page)
  await expect(page.locator('#confirm')).toBeVisible()
  await page.clock.runFor(5_000)
  await expect(page.locator('#confirm'), 'still showing at 5 s').toBeVisible()
  await page.clock.runFor(2_000)
  await expect(page.locator('#sheet'), 'back to the grid after 6 s').toHaveCount(0)
  await expect(card(page, 'c_ava')).toContainText('In since 9:00 AM')
})

test('a visit left open from last week: the card says Still signed in from Tue Sep 8, 8:05 AM. Not signed out.', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  const door = await doorToken(request)
  await signInViaApi(request, door, 'c_ruby', 'p_ruby_mother', { now: at('2026-09-08T08:05:00-02:30') })
  await signInViaApi(request, door, 'c_ben', 'p_ben_mother')
  await setUpTablet(page)
  const ruby = card(page, 'c_ruby')
  await expect(ruby).toHaveAttribute('data-status', 'in')
  await expect(ruby, 'the card tells the truth about an old open visit').toContainText('Still signed in from Tue Sep 8, 8:05 AM. Not signed out.')
  await expect(ruby).not.toContainText('In since')
  await expect(card(page, 'c_ben'), 'a child signed in today still reads In since').toContainText('In since 9:00 AM')
  // Ruby's card is below the fold with all 19 children; the Preschool room chip brings it into view for the screenshot.
  await tap(page, page.locator('button.chip[data-room="r_preschool"]'), 'Preschool room chip')
  await expect(ruby).toBeInViewport()
  await shot(page, testInfo, 'door', '7-still-signed-in-from-last-week')
  await tap(page, ruby, 'Ruby card')
  await expect(page.locator('#sheet .status-line')).toHaveText('Still signed in from Tue Sep 8, 8:05 AM. Not signed out.')
  await expect(page.locator('#action-out'), 'the child can still be signed out').toBeVisible()
})

test('status pills: short labels stay on one line at 1024×768; the long Still signed in label wraps inside its box', async ({ page, context, request }, testInfo) => {
  await fresh(context, request)
  const door = await doorToken(request)
  const t1245 = at('2026-09-14T12:45:00-02:30')
  await signInViaApi(request, door, 'c_ava', 'p_ava_mother', { now: t1245 })
  await signInViaApi(request, door, 'c_liam', 'p_liam_mother', { now: at('2026-09-14T08:15:00-02:30') })
  await signOutViaApi(request, door, 'c_liam', 'p_liam_father', { now: t1245 })
  await signInViaApi(request, door, 'c_ruby', 'p_ruby_mother', { now: at('2026-09-08T08:05:00-02:30') })
  await setUpTablet(page)
  expect(page.viewportSize()).toEqual({ width: 1024, height: 768 })
  const pill = (id) => card(page, id).locator('.status-pill')
  // Read-only measures: hidden overflow, lines of text inside the padding and border, and the pill's right edge inside its card.
  const measure = (id) => pill(id).evaluate((el) => {
    const cs = getComputedStyle(el)
    const inner = el.getBoundingClientRect().height - parseFloat(cs.paddingTop) - parseFloat(cs.paddingBottom)
      - parseFloat(cs.borderTopWidth) - parseFloat(cs.borderBottomWidth)
    return {
      overflow: el.scrollWidth - el.clientWidth,
      lines: Math.round(inner / parseFloat(cs.lineHeight)),
      inCard: el.getBoundingClientRect().right <= el.closest('button.child').getBoundingClientRect().right + 0.5,
    }
  })
  for (const [id, text] of [['c_ava', 'In since 12:45 PM'], ['c_liam', 'Gone home at 12:45 PM'], ['c_nora', 'Not in yet'], ['c_isla', 'Not booked today']]) {
    await expect(pill(id)).toHaveText(text)
    const m = await measure(id)
    expect(m.overflow, `${text}: nothing hidden`).toBeLessThanOrEqual(0)
    expect(m.lines, `${text} stays on one line`).toBe(1)
    expect(m.inCard, `${text}: inside its card`).toBe(true)
  }
  await expect(pill('c_ruby')).toHaveText('Still signed in from Tue Sep 8, 8:05 AM. Not signed out.')
  const long = await measure('c_ruby')
  expect(long.overflow, 'the long label: nothing hidden').toBeLessThanOrEqual(0)
  expect(long.inCard, 'the long label wraps inside its card').toBe(true)
  await shot(page, testInfo, 'door', '8-status-pills')
})

test('a device token that stops working brings back Set up this tablet', async ({ page, context, request }) => {
  await fresh(context, request)
  await setUpTablet(page)
  const token = await page.evaluate(() => localStorage.getItem('daycare-day-sheet:door-token'))
  expect((await api(request, 'POST', '/api/signout', null, bearer(token))).status).toBe(200)
  await tap(page, card(page, 'c_ava'), 'Ava card')
  await expect(page.getByRole('heading', { name: 'Set up this tablet' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('daycare-day-sheet:door-token'))).toBeNull()
})
